AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Style/RedundantFreeze:
  Enabled: false
