version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/ledger.api
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: ledger.api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: ledger.api-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: sudo apt install postgresql-client
      - run: bundle exec rake db:create
      - run: bundle exec rake db:structure:load

      # Run rspec
      - type: shell
        command: bundle exec rspec --require rails_helper -f d spec
