# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  auth0_domain: ledger-staging.eu.auth0.com
  auth0_api_audience: https://staging.api.my-ledger.com
  secret_key_base: 9f93933ef753aa71f7a4deedb951467a4ee0b3ed59abc2a9bed2b1baa087616b03764b7afcd242936530c692be9bbe1b016ad628bdcae7a04dbeb2f44988f230

test:
  auth0_domain: ledger-test.test.com
  auth0_api_audience: https://api.test.com
  secret_key_base: d55b199bbfae547a71f9c80896a4dea2d074d43f4554a5b39f4a428452c411e2d1863bf9e817c77b72ebff4de46a9593203ac3050e99b8620f9e367f1bdd2a20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_AUDIENCE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
